const fs = require('fs');
const filePath = 'src/app/servicos/ServicosClientPage.tsx';
let content = fs.readFileSync(filePath, 'utf-8');

const newServicesJs = \const services = {
  pt: [
    {
      id: 'consular',
      icon: '🛂',
      title: 'Documentação Consular',
      subtitle: 'Passaportes, Certidões e Registros',
      description: 'Auxiliamos na preparação, conferência e orientação da documentação necessária para procedimentos junto aos consulados brasileiros nos Estados Unidos, reduzindo erros, recusas e retrabalho.',
      docsTitle: 'Serviços consulares',
      howTitle: 'Como funciona',
      steps: [
        'Você nos envia seus documentos para análise gratuita',
        'Verificamos tudo de acordo com os requisitos do consulado',
        'Preparamos e orientamos cada etapa do processo',
        'Acompanhamos sua solicitação até a conclusão',
      ],
      docs: ['Passaporte / renovação de passaporte', 'Atestado de residência e de vida', 'CPF e Título eleitoral', 'Autorização de viagem para menores', 'Certidões de nascimento e casamento', 'Alistamento e dispensa militar', 'Matrícula consular', 'Reconhecimento de assinatura e cópias'],
      warning: 'O consulado pode recusar documentos por erros mínimos. Nossa análise prévia evita esse problema.',
    },
    {
      id: 'vistos',
      icon: '✈️',
      title: 'Vistos',
      subtitle: 'Autorização de entrada',
      description: 'Assessoria para diferentes modalidades de visto de entrada e permanência no Brasil, de acordo com a nacionalidade e a situação de cada solicitante. O VITEM XI é destinado aos casos de estrangeiros que precisam realizar processo de reunificação familiar no Brasil.',
      docsTitle: 'Principais vistos',
      howTitle: 'Como funciona',
      steps: [
        'Analisamos sua nacionalidade e finalidade da viagem',
        'Orientamos a organização da documentação necessária',
        'Realizamos o preenchimento dos formulários exigidos',
        'Acompanhamos o processo até a emissão do visto',
      ],
      docs: ['e-Visa para cidadãos americanos', 'e-Visa para cidadãos canadenses', 'VIVIS / visto de visitante', 'Assessoria para dupla nacionalidade', 'VITEM XI (reunificação familiar)'],
      warning: null,
    },
    {
      id: 'legalizacao',
      icon: '⚖️',
      title: 'Legalização e Traduções',
      subtitle: 'Validade de Documentos',
      description: 'Auxiliamos na preparação de documentos emitidos nos Estados Unidos para que possam ser utilizados no Brasil, além de serviços de tradução conforme a necessidade de cada processo.',
      docsTitle: 'Serviços de legalização',
      howTitle: 'Como funciona',
      steps: [
        'Avaliamos os documentos emitidos nos EUA',
        'Orientamos sobre a necessidade de apostilamento',
        'Auxiliamos no processo de tradução se necessário',
        'Preparamos os documentos para envio ao Brasil',
      ],
      docs: ['Legalização de documentos americanos para uso no Brasil', 'Apostilamento de Haia', 'Traduções certificadas nos EUA', 'Traduções juramentadas no Brasil'],
      warning: null,
    },
    {
      id: 'procuracoes',
      icon: '📋',
      title: 'Procurações Públicas',
      subtitle: 'Poder Legal a Distância',
      description: 'Fazemos procurações públicas para diferentes finalidades, com elaboração e orientação de todo o processo. O procedimento pode ser realizado via Consulado Brasileiro ou via cartório no Brasil, conforme a necessidade de cada caso.',
      docsTitle: 'Tipos de procurações',
      howTitle: 'Como funciona',
      steps: [
        'Você nos informa a finalidade da procuração.',
        'Elaboramos a procuração pública de acordo com a necessidade do processo.',
        'Orientamos o procedimento de reconhecimento de assinatura via Consulado ou Notário Público, conforme o caso.',
      ],
      docs: ['Venda de imóvel', 'Transações bancárias', 'Representação perante o INSS', 'Inventário', 'Matrícula escolar', 'Procurações para outras finalidades'],
      warning: 'Procurações mal redigidas podem ser recusadas no cartório brasileiro. Garantimos a redação correta.',
    },
    {
      id: 'enotariado',
      icon: '🔐',
      title: 'e-Notariado',
      subtitle: 'Atos Notariais Eletrônicos',
      description: 'O e-Notariado é a plataforma utilizada pelos cartórios de notas brasileiros para a realização de atos notariais eletrônicos. Ela permite que determinados procedimentos sejam realizados digitalmente e à distância, facilitando o acesso a serviços cartorários para brasileiros que vivem no exterior. A Atheros auxilia e orienta o cliente durante o processo de utilização do e-Notariado, de acordo com o ato notarial necessário.',
      docsTitle: 'Para que serve?',
      howTitle: 'Passo a passo',
      steps: [
        'Avaliamos a sua necessidade para serviços notariais',
        'Orientamos como acessar e utilizar o e-Notariado',
        'Acompanhamos a realização do procedimento à distância',
      ],
      docs: ['Realização de atos notariais eletrônicos', 'Assinaturas relacionadas a atos notariais', 'Procedimentos digitais com cartórios brasileiros', 'Atendimento remoto em procedimentos compatíveis com a plataforma'],
      warning: null,
    },
  ],
  en: [
    {
      id: 'consular',
      icon: '🛂',
      title: 'Consular Documentation',
      subtitle: 'Passports, Certificates and Registrations',
      description: 'We assist in the preparation, conference and guidance of the documentation required for procedures with Brazilian consulates in the United States, reducing errors, rejections and rework.',
      docsTitle: 'Consular services',
      howTitle: 'How it works',
      steps: [
        'You send us your documents for free analysis',
        'We verify everything according to consulate requirements',
        'We prepare and guide each step of the process',
        'We monitor your request until completion',
      ],
      docs: ['Passport / passport renewal', 'Residence and life certificate', 'CPF and Voter registration', 'Travel authorization for minors', 'Birth and marriage certificates', 'Military enlistment and dismissal', 'Consular registration', 'Signature recognition and copies'],
      warning: 'The consulate can reject documents for minor errors. Our prior analysis prevents this problem.',
    },
    {
      id: 'vistos',
      icon: '✈️',
      title: 'Visas',
      subtitle: 'Entry Authorization',
      description: 'Advisory for different types of entry and stay visas in Brazil, according to the nationality and situation of each applicant. VITEM XI is intended for cases of foreigners who need to carry out family reunification procedures in Brazil.',
      docsTitle: 'Main visas',
      howTitle: 'How it works',
      steps: [
        'We analyze your nationality and purpose of travel',
        'We guide the organization of the necessary documentation',
        'We complete the required forms',
        'We monitor the process until the visa is issued',
      ],
      docs: ['e-Visa for American citizens', 'e-Visa for Canadian citizens', 'VIVIS / visitor visa', 'Visa assistance for dual nationality', 'VITEM XI (family reunification)'],
      warning: null,
    },
    {
      id: 'legalizacao',
      icon: '⚖️',
      title: 'Legalization and Translations',
      subtitle: 'Document Validity',
      description: 'We assist in preparing documents issued in the United States so they can be used in Brazil, in addition to translation services according to the needs of each process.',
      docsTitle: 'Legalization services',
      howTitle: 'How it works',
      steps: [
        'We evaluate documents issued in the USA',
        'We provide guidance on the need for apostilles',
        'We assist with the translation process if necessary',
        'We prepare documents to be sent to Brazil',
      ],
      docs: ['Legalization of American documents for use in Brazil', 'Hague Apostille', 'Certified translations in the USA', 'Sworn translations in Brazil'],
      warning: null,
    },
    {
      id: 'procuracoes',
      icon: '📋',
      title: 'Public Powers of Attorney',
      subtitle: 'Legal Power at a Distance',
      description: 'We prepare public powers of attorney for different purposes, with elaboration and guidance throughout the process. The procedure can be carried out via the Brazilian Consulate or via a registry office in Brazil, according to the needs of each case.',
      docsTitle: 'Types of POAs',
      howTitle: 'How it works',
      steps: [
        'You tell us the purpose of the power of attorney.',
        'We draft the public power of attorney according to your needs.',
        'We guide the signature recognition procedure via Consulate or Notary Public, as appropriate.',
      ],
      docs: ['Real estate sale', 'Banking transactions', 'Social Security representation', 'Estate proceedings', 'School enrollment', 'POAs for other purposes'],
      warning: 'Poorly drafted powers of attorney may be rejected at Brazilian notary offices. We guarantee correct drafting.',
    },
    {
      id: 'enotariado',
      icon: '🔐',
      title: 'e-Notariado',
      subtitle: 'Electronic Notarial Acts',
      description: 'e-Notariado is the platform used by Brazilian notary offices to perform electronic notarial acts. It allows certain procedures to be carried out digitally and remotely, facilitating access to notary services for Brazilians living abroad. Atheros guides and assists clients during the process of using e-Notariado, according to the required notarial act.',
      docsTitle: 'What is it for?',
      howTitle: 'Step by step',
      steps: [
        'We assess your need for notarial services',
        'We guide you on how to access and use e-Notariado',
        'We assist with the remote execution of the procedure',
      ],
      docs: ['Performance of electronic notarial acts', 'Signatures related to notarial acts', 'Digital procedures with Brazilian registries', 'Remote service in compatible procedures'],
      warning: null,
    },
  ],
};\;

content = content.replace(/const services = \{[\s\S]*?\n\};\n\nconst t = \{/, newServicesJs + '\n\nconst t = {');
fs.writeFileSync(filePath, content, 'utf-8');
console.log('Done!');
